export default {
  history: [],
  isMobile: false,
  step: 1,
  showViewer: false,
  loading: false,
  notifyTimeout: 2000,
  isFirstEnter: false,
  statusBar: null,
  isEducation: false,
  processTour: null,
  tours: {
    homeTour: false,
    menuTour: false,
    coreTour: false,
    lifeTour: false,
    tasksTour: false,
    p2pTour: false,
    stakingTour: false,
    lifeTasksTour: false,
    tasksTour: false
  },
  renderGlobe: true,
  community: null,
  cmsConfig: null,
  signProcess: false,
  regComplete: false,
  showDescriptor: true,
  leftDrawer: false,
  rightDrawer: false,
  root_content: [],
  enter_name: false,
  enter_params: false,
  singleEdu: false,
  back_to: null,
  back_to_params: {},
}
