export default {
  verified: undefined,
  username: undefined,
  partner: {},
  all_partners: [],
  all_usdt_withdraws: [],
  last_partner_id: 0,
  site_type: undefined,
  target_host: undefined,
  target_page: "index",
  target_params: {},
  balance: [],
  token_stat: {token: {}, users: []},
  hostname: undefined,
  deposit_amount: 0,
  host_obj: false,
  orderToken: null,
  principals: [],
  principal: null,
  sys_percent: 0,
  params:[],
  pools:[],
  cycles: [],
  rates:[],
  goals: [],
  events: [],
  tokens: [],
  orders: [],
  methods: [],
  incoming: [],
  doers: [],
  spiral: null,
  spiral2: null,
  categories: [],
  locations: [],
  roles: [],
  user_marathons: [],
  bwtradegraph: [{
        data: [],
    }],
  current_goal: null,
  reports: [],
  badges: [],
  usbadges: [],
  tasks: [],
  dacs: [],
  vacs: [],
  vproposals: [],
  sincome: [],
  comments:[],
  referals: [],
  conditions: [{
    key_string: 'minpower',
    value: 0,
  }],
  minpower: 0,
  current_pool: {},
  current_target_pool: null,
  next_current_target_pool_rate: 0,

  current_pool_color: "",
  isblack: false,
  remain_quants: "",
  percent: 0,
  total_in_box: "",
  quant_cost: "",
  float_quant_cost: 0,
  remain_quants_in_tokens: "",
  priority_between: "",
  priority_seconds: 0,
  pool_expired: 0,
  expired_flag: false,
  orderDialog: false,
  total_growth: "",
  sell_rate: "",
  buy_rate: "",
  emission: [],
  market: [],
  upower: [],
  series: [{
    data: [],
    }],
  after: undefined,
  orderby: "created_ASC",
  ahosts: [],
  coreahosts: [],
  usdrates: [],
  cfund: null,
  pvests: [],
  p2pvests: [],
  dhistory: [],
  cmscontent: [],
  is_base: false,
  hostsonfunds: [],
  gfunds: [],
  reg_balance: null,
}
