export default {
  manifest: undefined,
  owner: undefined,
  author: undefined,
  permlink: undefined,
  parentAuthor: undefined,
  parentPermlink: undefined,
  type: undefined,
  after: undefined,
  orderby: "created_ASC",
  show: false,
  path: [],
  newFolder: '',
  dbs_online: [],
  accessRight: {
    read: false,
    write: false,
    admin: false
  },
  item: null,
  cursor: null,
  prevFolderCursor: null,
  items: [],
  goals: [],
  cfund: null,
  goal: null,
  tasks: [],
  reports: [],
  prevItems: [],
  public: [],
  needFetchPath: false,
  showUpButton: false,
  needSave: false,
  needDelete: false,
  needOpen:{
    flag: false,
    address: ''
  },
  needLoad: false,
  needAdd: {
    flag: false,
    type: ''
  },
  showSettings: false,
  sortNow: false,
  makePublic: false,
  makePrivate: false,
  showFolderDialog: false,
  enter_name: false,
  enter_params: false,
}
